#!/bin/bash
# $Id: sysinstall,v 1.1 2013/07/29 07:29:48 root Exp root $
# $Source: /root/opengks/RCS/sysinstall,v $
# DESC: OpenGKS - SYSINSTALL
# AUTHOR: Eric Fajardo / eric@arpa.ph

# THE OPENGKS DEVELOPER INSTALLER.
# THIS SHOULD INSTALL AND LOAD THE NECESSARY PRE-REQUISITES AND CONFIG FILES.

DIR=/root/opengks
VER="OpenGKS v1.1"
export DEBIAN_FRONTEND=noninteractive

# [C] CONFIGURATION
/usr/sbin/usermod -c "How are you today?" opengks
/bin/sed -i 's/#//' /etc/default/kannel
/usr/sbin/usermod -aG dialout kannel

/etc/init.d/apparmor stop
/etc/init.d/apparmor teardown
update-rc.d -f apparmor remove

# [S] SETUP
cd $DIR/opengks/crikey-0.8.3
make
make install
cd $DIR/opengks/gtkdialog-0.8.3
./configure
make
make install
cd$DIR/opengks/shc-3.8.9
make
make install

# [B] BUILD
cd $DIR/opengks/bin/OpenGKS
for i in `ls -1 . | sed 's#.*/##'`; { shc -f $i; mv $i.x $i; rm -f $i.x.c; }

cp -R $DIR/opengks/etc/* /etc/.
cp -R $DIR/opengks/home/.config /home/opengks/.
cp -R $DIR/opengks/home/.ssh /home/opengks/.
cp -R $DIR/opengks/home/.xsession /home/opengks/.
cp -R $DIR/opengks/home/.Xdefaults /home/opengks/.
cp -R $DIR/opengks/bin/OpenGKS /usr/local/bin/.
cp -R $DIR/opengks/www /var/.

mkdir -p /etc/OpenGKS/bin
cp -R $DIR/opengks/tmp/showreadme /etc/OpenGKS/bin/.
cp -R $DIR/opengks/tmp/createdb /etc/OpenGKS/bin/.
cp -R $DIR/opengks/tmp/opengks.sql /etc/OpenGKS/bin/.
cp -R $DIR/opengks/tmp/grub /etc/default/.
cp -R $DIR/opengks/tmp/drustan_nebula_by_casperium.jpg /usr/share/backgrounds/.
cp -R $DIR/opengks/tmp/drustan_nebula_by_casperium.jpg /usr/share/backgrounds/warty-final-ubuntu.png
cp -R $DIR/opengks/tmp/10_unity_greeter_background.gschema.override /usr/share/glib-2.0/schemas/.
cp -R $DIR/opengks/tmp/ubuntu-wallpapers.xml /usr/share/gnome-background-properties/.
cp -R $DIR/opengks/tmp/precise-wallpapers.xml /usr/share/gnome-background-properties/.

/bin/tar -zxf $DIR/opengks/gks-theme.tgz -C /lib/plymouth/themes/
/usr/sbin/update-alternatives --install /lib/plymouth/themes/default.plymouth default.plymouth /lib/plymouth/themes/gks-theme/gks-theme.plymouth 100

/bin/ln -s /usr/local/bin/OpenGKS/prod.mailer.gk /usr/bin/mailer
/bin/ln -s /usr/local/bin/OpenGKS/prod.timein.gk /usr/bin/timein
/bin/ln -s /usr/local/bin/OpenGKS/prod.gencfvar.gk /usr/bin/genconfig
/bin/ln -s /usr/local/bin/OpenGKS/prod.control.gk /usr/bin/control
/bin/ln -s /usr/local/bin/OpenGKS/prod.open.gk /usr/bin/opengks
/bin/ln -s /usr/local/bin/OpenGKS/prod.sendsms.gk /usr/bin/sendsms
/bin/ln -s /etc/OpenGKS/bin/showreadme /usr/bin/showreadme

cd /tmp
if [[ "`uname -i`" == "x86_64" ]]; then
	wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
	dpkg -i /tmp/google-chrome-stable_current_amd64.deb
else
	wget "https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
	dpkg -i /tmp/google-chrome-stable_current_i386.deb
fi

mkdir -p /home/opengks/TOOLBOX
ln -s /usr/bin/google-chrome-stable /home/opengks/TOOLBOX/Chrome
ln -s /usr/bin/xterm /home/opengks/TOOLBOX/Xterm 

# [S] SECURITY
/bin/chmod 666 /etc/ssh/sshd_config
/bin/echo "Banner /etc/banner" >> /etc/ssh/sshd_config
/bin/echo "AllowUsers      opengks" >> /etc/ssh/sshd_config
/bin/chmod 600 /etc/ssh/sshd_config

# SSL CONFIGURATION
echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf
/usr/sbin/a2enmod ssl
/usr/sbin/a2enmod rewrite
/usr/sbin/a2ensite default-ssl
/etc/init.d/apache2 restart

# FORCING IPV4
sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
sed -i 's/inet_protocols = all/inet_protocols = ipv4/g' /etc/postfix/main.cf
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf

# SYSTEM REBOOT
sudo a2enmod rewrite
chown -R opengks:opengks /home/opengks
chmod +x $DIR/opengks/bin/OpenGKS
/usr/sbin/update-grub2
/usr/sbin/update-initramfs -u
/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
shutdown -r now
exit 0
